.PHONY: all pdf FORCE_MAKE

all pdf:: main.pdf

%.pdf: %.tex FORCE_MAKE
	latexmk -pdf $<

clean::
	latexmk -c
.PHONY: all pdf FORCE_MAKE

all pdf:: main.pdf

%.pdf: %.tex FORCE_MAKE
	latexmk -pdf $<

clean::
	latexmk -c

